apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: deployment
  labels:
    type: reverse-proxy
spec:
  replicas: 50
  selector:
    matchLabels:
      type: reverse-proxy
  template:
    metadata:
      name: nginx
      labels:
        type: reverse-proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        # resources:
        #   requests:
        #     memory: "3Gi"
        #     cpu: "0.5"
        #   limits:
        #     memory: "3Gi"
        #     cpu: "750m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    type: reverse-proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

