apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    type: reverse-proxy
spec:
  replicas: 20
  selector:
    matchLabels:
      type: reverse-proxy
  template:
    metadata:
      name: nginx
      labels:
        type: reverse-proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "3Gi"
            cpu: "0.5"
          limits:
            memory: "3Gi"
            cpu: "750m"
