apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    type: reverse-proxy
spec:
  replicas: 16
  selector:
    matchLabels:
      type: reverse-proxy
  template:
    metadata:
      name: nginx
      labels:
        type: reverse-proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "500Mi"
            cpu: "750m"
        ports:
        - containerPort: 80
          hostPort: 80
