apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    type: reverse-proxy
spec:
  replicas: 16
  selector:
    matchLabels:
      type: reverse-proxy
  template:
    metadata:
      name: nginx
      labels:
        type: reverse-proxy
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            memory: "4Gi"
            cpu: "0.2"
          limits:
            memory: "4Gi"
            cpu: "0.3"
