apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-monitoring
spec:
  limits:
  - default: # this sesction defines default limits 
      cpu: "0.5"
    defaultRequest: # thi is section defines defalt requests
      cpu: "0.5"
    max: # the max and min define the limit range
      cpu: "1"
    min:
      cpu: "0.3"
    type: Container
