apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv-1
spec:
  capacity:
    storage: 25Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: "vol-05a12322a52ebf6db"
    fsType: ext4
#vol-07a34f87ee5f87cbb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv-2
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  awsElasticBlockStore:
    volumeID: "vol-07eebef559e8125fe"
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: html
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: ebs-static-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  #namespace: default
  labels:
    name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
