apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStorage:
    volumeID: "vol-06c4aae20aafa7bcc"
    fsType: ext4
