apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-service
    environment: DEV
spec:
  type: LoadBalancer
  selector:
    project: eksctl
    environment: dev
    component: nginx
  ports:
  - name: http-port
    protocal: tcp
    # service port
    port: 80
    # pod port
    targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    project: eksctl
    environment: dev
    component: nginx
spec:
  containers:
  - name: nginx
    image: nginx

